# -*- mode:python -*-
#
""" Fault Injection Module to Gem5
    Version 1.0
    02/02/2016
    
    Author: Felipe Rocha da Rosa - frdarosa.com
"""
#

Import('*')


SimObject('FaultInjectionSystem.py')

Source('FaultInjectionSystem.cc')
