IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")

CFLAGS += -I.
CFLAGS += -I$(IMPERAS_HOME)/ImperasLib/source
CFLAGS += -I$(IMPERAS_HOME)/ImpPublic/include/host/isl

include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.host
